const extractDtoProperties = ({ inTransformation, inResultKey }) => {
    const localTransformation = inTransformation;
    const localResultKey = inResultKey;

    if (!localTransformation || !localResultKey) {
        return [];
    }

    const keySchema = localTransformation[localResultKey]?.transform;
    if (!keySchema || typeof keySchema !== "object") {
        return [];
    }

    const properties = [];
    for (const [, fieldSpec] of Object.entries(keySchema)) {
        if (!fieldSpec) continue;
        const alterKey = typeof fieldSpec === "object" ? fieldSpec.alterKey : null;
        if (!alterKey) continue;

        const isArray = fieldSpec.valueType === "array" || fieldSpec.transform !== undefined;
        const typeStr = isArray ? "any[]" : "string";
        properties.push(`    ${alterKey}?: ${typeStr};`);
    }

    return properties;
};

const renderTree = ({ inNode, inLevel = 0, inParentPath = [] }) => {
    const localNode = inNode;
    const localLevel = inLevel;
    const localParentPath = inParentPath;

    const indent = "    ".repeat(localLevel);
    const childIndent = "    ".repeat(localLevel + 1);
    const lines = ["{"];

    for (const [key, value] of Object.entries(localNode)) {
        if (key.startsWith("__")) continue;

        const currentPath = [...localParentPath, key];
        const isEndpoint = value.__endpoint === true;
        const description = value.__description || `Runs ${currentPath.join(".")}.`;
        const nestedKeys = Object.keys(value).filter((childKey) => !childKey.startsWith("__"));

        if (isEndpoint && nestedKeys.length === 0) {
            lines.push(`${childIndent}/** ${description} */`);
            lines.push(`${childIndent}${key}: (inParam: string, ...inArgs: any[]) => Promise<any>;`);
            continue;
        }

        lines.push(
            `${childIndent}${key}: ${renderTree({
                inNode: value,
                inLevel: localLevel + 1,
                inParentPath: currentPath
            })};`
        );
    }

    lines.push(`${indent}}`);
    return lines.join("\n");
};

const startFunc = ({ inDefinition }) => {
    const localDefinition = inDefinition;
    const { version, rootName, tree } = localDefinition;

    const dtos = [];
    const collectedDtoNames = new Set();

    const collectDtos = (node) => {
        for (const [key, value] of Object.entries(node)) {
            if (key.startsWith("__")) continue;
            if (value.__endpoint && value.__resultKey && value.__transformation) {
                const dtoName = `${value.__resultKey.replace(/s$/, "")}Dto`;
                if (!collectedDtoNames.has(dtoName)) {
                    collectedDtoNames.add(dtoName);
                    const props = extractDtoProperties({
                        inTransformation: value.__transformation,
                        inResultKey: value.__resultKey
                    });

                    if (props.length > 0) {
                        dtos.push(`export interface ${dtoName} {\n${props.join("\n")}\n    [key: string]: any;\n}`);
                    }
                }
            }
            collectDtos(value);
        }
    };

    collectDtos(tree);

    const apiTree = tree[rootName] ? tree[rootName] : tree;
    const typeName = `${rootName.charAt(0).toUpperCase() + rootName.slice(1)}Api`;

    const dtoSection = dtos.length > 0 ? `${dtos.join("\n\n")}\n\n` : "";

    return `/**
 * Generated by create-intellisense from src/${version.name}.
 * Do not edit this file directly.
 */

${dtoSection}export type ${typeName} = ${renderTree({
    inNode: apiTree,
    inLevel: 0,
    inParentPath: [rootName]
})};

declare const ${rootName}: ${typeName};

export default ${rootName};
`;
};

export default startFunc;
